name: "Mine Data (Websites)"

on:
  schedule:
    - cron: '*/60 * * * *'
  workflow_dispatch:

jobs:
  minedata_websites:
    name: "Download data from websites"
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        ref: websites

    - name: Checkout tools branch
      uses: actions/checkout@v3
      with:
        repository: Unturned-Datamining/datamining-tool
        path: tools

    - uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '7.0.x'

    - name: Install dependencies
      run: dotnet restore tools/UnturnedDatamining/

    - name: Run tool
      run: dotnet run --project ./tools/UnturnedDatamining/UnturnedDatamining/UnturnedDatamining.csproj -c Release --no-restore -- $GITHUB_WORKSPACE websites

    - name: Generate Commit Message
      run: |
        msg=$( cat .commit )
        echo "message=$msg" >> "$GITHUB_OUTPUT"
      id: generate_commit_message

    - run: |
        git config --global user.email "diffoz@users.noreply.github.com"
        git config --global user.name "DiFFoZ"

        git add .
        git commit -m "${{ steps.generate_commit_message.outputs.message }}"
        git push
