name: "Mine Data (Game)"

on:
  schedule:
    - cron: '*/60 * * * *'
  workflow_dispatch:

jobs:
  minedata_client:
    name: "Setup Steam and Unturned and decompile"
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        ref: linux-client-preview

    - name: Checkout tools branch
      uses: actions/checkout@v4
      with:
        repository: Unturned-Datamining/datamining-tool
        path: tools

    - name: Setup SteamCMD
      id: setup-steamcmd
      uses: CyberAndrii/setup-steamcmd@v1

    - name: Update app
      run: steamcmd +force_install_dir $GITHUB_WORKSPACE +login ${{ secrets.STEAM_USERNAME }} ${{ secrets.STEAM_PASSWORD }} +app_update 304930 -beta preview -validate +quit

    - uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - name: Install dependencies
      run: dotnet restore tools/UnturnedDatamining/

    - name: Run tool
      if: ${{ github.event_name == 'workflow_dispatch' }}
      run: dotnet run --project ./tools/UnturnedDatamining/UnturnedDatamining/UnturnedDatamining.csproj -c Release --no-restore -- $GITHUB_WORKSPACE decompile --force --client

    - name: Run tool
      if: ${{ github.event_name == 'schedule' }}
      run: dotnet run --project ./tools/UnturnedDatamining/UnturnedDatamining/UnturnedDatamining.csproj -c Release --no-restore -- $GITHUB_WORKSPACE decompile --client

    - name: Generate Commit Message
      run: |
        msg=$( cat .commit )
        echo "message=$msg" >> "$GITHUB_OUTPUT"
      id: generate_commit_message

    - run: |
        git config --global user.email "diffoz@users.noreply.github.com"
        git config --global user.name "DiFFoZ"

        git add -A
        git status
        git commit -m "${{ steps.generate_commit_message.outputs.message }}"
        git push
